owner: schliesser
repo: upptime

sites:
  - name: EC-Balzheim
    url: https://www.ec-balzheim.de
  - name: Highlanders
    url: https://highlanders.club
  - name: VertexDezign
    url: https://vertexdezign.net
  - name: Nextcloud
    url: $NEXTCLOUD_URL
    icon: https://status.schliesser.dev/nextcloud.png
  - name: MinIO
    url: $MINIO_URL
    icon: https://status.schliesser.dev/minio.png

assignees:
  - schliesser

status-website:
  cname: status.schliesser.dev
  robotsText: "User-agent: * \n Disallow: /"
  name: "schliesser.dev status"
  introTitle: "Uptime monitor"
  introMessage: "This is a status page for schliesser.dev projects."
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: schliesser

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
