owner: schliesser
repo: upptime

sites:
  - name: EC-Balzheim
    url: https://www.ec-balzheim.de
    icon: https://status.schliesser.dev/ec-balzheim.png
    type: globalping
    location: germany
  - name: Highlanders
    url: https://highlanders.club
    icon: https://status.schliesser.dev/highlanders.png
    type: globalping
    location: germany
  - name: VertexDezign
    url: https://vertexdezign.net
    icon: https://status.schliesser.dev/vertexdezign.png
    type: globalping
    location: germany
  - name: Nextcloud
    url: $NEXTCLOUD_URL
    icon: https://status.schliesser.dev/nextcloud.png
    type: globalping
    location: germany
  - name: MinIO
    url: $MINIO_URL
    icon: https://status.schliesser.dev/minio.png
    type: globalping
    location: germany
  - name: Surfcamp TYPO3 Team Success
    url: https://success.surfcamp.schliesser.dev/
    type: globalping
    location: germany
  - name: Audiobookshelf
    url: $AUDIOBOOKSHELF_URL
    icon: https://status.schliesser.dev/audiobookshelf.png
    type: globalping
    location: germany

assignees:
  - schliesser

status-website:
  cname: status.schliesser.dev
  robotsText: "User-agent: * \n Disallow: /"
  logoUrl: https://status.schliesser.dev/upptime-icon.svg
  name: "Upptime"
  introTitle: "schliesser.dev Uptime Monitor"
  introMessage: "This is a status page for schliesser.dev projects."
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: schliesser

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
